const vocabulary = {
  en: {
    0: 'Sunday',
    1: 'Monday',
    2: 'Tuesday',
    3: 'Wednesday',
    4: 'Thursday',
    5: 'Friday',
    6: 'Suturday',
    longitude: 'Longitude',
    latitude: 'latitude',
    Jan: 'January',
    Feb: 'February',
    Mar: 'March',
    Apr: 'April',
    May: 'May',
    Jun: 'June',
    Jul: 'July',
    Aug: 'August',
    Sep: 'September',
    Oct: 'October',
    Nov: 'November',
    Dec: 'December',
    Sun: 'Sun',
    Mon: 'Mon',
    Tue: 'Tuesday',
    Wed: 'Wed',
    Thu: 'Thu',
    Fri: 'Fri',
		Sut: 'Sut',
		info: 'Click on a country to get a weather forecast',
  },
  be: {
    0: 'Нядзеля',
    1: 'Панядзелак',
    2: 'Аўторак',
    3: 'Серада',
    4: 'Чацвер',
    5: 'Пятнiца',
    6: 'Субота',
    longitude: 'Даўгата',
    latitude: 'Шырата',
    Jan: 'Студзень',
    Feb: 'Люты',
    Mar: 'Сакавiк',
    Apr: 'Красавiк',
    May: 'Май',
    Jun: 'Червень',
    Jul: 'Лiпень',
    Aug: 'Жнiвень',
    Sep: 'Верасень',
    Oct: 'Кастрычнiк',
    Nov: 'Лiстапад',
    Dec: 'Снежань',
    Sun: 'Нд',
    Mon: 'Пн',
    Tue: 'Аў',
    Wed: 'Ср',
    Thu: 'Чц',
    Fri: 'Пт',
		Sut: 'Сб',
		info: `Націсніце на краіну каб атрымаць прагноз надвор'я`
  },
  ru: {
    0: 'Воскресенье',
    1: 'Понедельник',
    2: 'Вторник',
    3: 'Среда',
    4: 'Четверг',
    5: 'Пятница',
    6: 'Суббота',
    longitude: 'Долгота',
    latitude: 'Широта',
    Jan: 'Январь',
    Feb: 'Февраль',
    Mar: 'Март',
    Apr: 'Апрель',
    May: 'Май',
    Jun: 'Июнь',
    Jul: 'Июль',
    Aug: 'Август',
    Sep: 'Сентябрь',
    Oct: 'Октябрь',
    Nov: 'Ноябрь',
    Dec: 'Декабрь',
    Sun: 'Вс',
    Mon: 'Пн',
    Tue: 'Вт',
    Wed: 'Ср',
    Thu: 'Чт',
    Fri: 'Пт',
		Sut: 'Сб',
		info: 'Нажмите на страну чтобы получить прогноз погоды'
  },
};

export default function translate(language, word) {
  return vocabulary[language][word];
}
